name: Deploy Databricks Bundle

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate Databricks Bundle
    runs-on: deepak-self-hosted-runner

    env:
      VAULT_ADDR: http://127.0.0.1:8200
      DATABRICKS_HOST: https://dbc-1d5bb94d-3a60.cloud.databricks.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Vault
        env:
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          VAULT_TOKEN=$(vault write -field=token auth/approle/login \
            role_id="$VAULT_ROLE_ID" \
            secret_id="$VAULT_SECRET_ID")

          echo "VAULT_TOKEN=$VAULT_TOKEN" >> "$GITHUB_ENV"

      - name: Retrieve Databricks credentials from Vault
        run: |
          echo "DATABRICKS_CLIENT_ID=$(vault kv get -field=client_id secret/databricks)" >> "$GITHUB_ENV"
          echo "DATABRICKS_CLIENT_SECRET=$(vault kv get -field=client_secret secret/databricks)" >> "$GITHUB_ENV"

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks Bundle
        run: databricks bundle validate -t dev

  deploy:
    name: Deploy Databricks Bundle
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    runs-on: deepak-self-hosted-runner

    env:
      VAULT_ADDR: http://127.0.0.1:8200
      DATABRICKS_HOST: https://dbc-1d5bb94d-3a60.cloud.databricks.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Vault
        env:
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          VAULT_TOKEN=$(vault write -field=token auth/approle/login \
            role_id="$VAULT_ROLE_ID" \
            secret_id="$VAULT_SECRET_ID")

          echo "VAULT_TOKEN=$VAULT_TOKEN" >> "$GITHUB_ENV"

      - name: Retrieve Databricks credentials from Vault
        run: |
          echo "DATABRICKS_CLIENT_ID=$(vault kv get -field=client_id secret/databricks)" >> "$GITHUB_ENV"
          echo "DATABRICKS_CLIENT_SECRET=$(vault kv get -field=client_secret secret/databricks)" >> "$GITHUB_ENV"

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Databricks Bundle
        run: databricks bundle deploy -t dev